Website = "https://github.com/dcvix/dcvix-stats"

[Details]
  Icon = "Icon.png"
  Name = "dcvix-stats"
  ID = "net.cortassa.dcvix-stats"
  Version = "1.2.0"
  Build = 1

[Migrations]
  fyneDo = true

[Source]
  Repo = "https://github.com/dcvix/dcvix-stats"
  Dir = "cmd/dcvix-stats"

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"

[LinuxAndBSD]
  GenericName = "dcvix Stats"
  Categories = ["System", "Monitor"]
  Comment = "Display statistics from a NICE DCV server log file."
  Keywords = ["DCV", "Monitor",  "Network", "Performance"]
